### ISSUE TITLE
Apparent stall of solver

### ISSUE THREAD

**Issue by jdtibochab** [SBRG/solvemepy#10]
When trying to solve any ME model I am getting stat=4 (apparent stall) and the example script getting_started.ipynb. I tried the "NaN value" fix listed in troubleshooting as I am seeing NaN values under "sinf" in the log solver, but it did not help. 

NaN values:
![image](https://user-images.githubusercontent.com/44821307/72024472-5be57100-322a-11ea-83cb-9e56a7e17c78.png)

**Comment by laurenceyang33** [comment]
Hello, thanks for trying the NaN value fix.
A similar stall was identified recently and traced to a different cause--the GCC version that Numpy was compiled with.
Please try out the approach here: https://docs.computecanada.ca/wiki/ME_modelling
(Probably using a virtualenv, to be safe.)
Specifically, this line:
Important: the Python compiler should be GCC > 5.4.0 Compiling numpy with this version is also necessary:
       pip install git+https://github.com/numpy/numpy@v1.16.0

**Comment by jdtibochab** [comment]
Thanks for your quick reply.

I have upgraded GCC from 4.8.4 to 5.5.0, compiled numpy 1.16.0 and reinstalled solvemepy, but it did not help with the issue. What else could I try to solve this?

**Comment by jdtibochab** [comment]
What did the trick was uninstalling anaconda and installing all packages.again. Apparently there was some path confusion and some things were being compiled with different anaconda environment GCC versions.

**Comment by laurenceyang33** [comment]
Glad to hear it worked! Thank you for posting this solution!
